namespace: image-moderation-api
replicas: 2
image:
  repository: hotspurs/image-moderation-api
  tag: latest
containerPort: 8003
hpa:
  minReplicas: 2
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70
service:
  nodePort: 30093
resources:
  requests:
    cpu: 100m
  limits:
    cpu: 600m
env:
  - name: API_KEY
    value: <path:services/data/image-moderation-api#TEST>