apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "image-moderation-api.namespace" . | default "image-moderation-api" }}
  labels:
    name: {{ include "image-moderation-api.namespace" . | default "image-moderation-api" }}